const CompanyInfo = [
  {
    index: 0,
    id: "ast",
    short_name: "A",
    name: "Astral Company Limited",
    overview:
      "Astral Company Limited (AST) is a car manufacturer that focuses on three mainstream: automotive, electric vehicle, and batteries. Starting in 2010, the company continues to invest in its electric vehicle and batteries business segments, aiming to establish its leading position in the two areas.",
    news_type: "31e2f577-9583-4864-b22d-21869fa422a8",
    industry: "IT",
    // opportunity1: ,
    // opportunity2: ,
    // risk1: ,
    // risk2: ,
    // snowflask: ,
  },
  {
    index: 1,
    id: "dsc",
    short_name: "D",
    name: "Doshacom",
    overview:
      "Doshacom is a leading provider of telecommunications, media, and technology services . The company offers wireless, wireline, satellite, and strategic data services, including Virtual Private Networks (VPN), Ethernet and broadband services. It is one of the biggest wireline and wireless providers in the US.",
    news_type: "534aaba1-a048-4c59-af4f-26ad5a951f9a",
    industry: "Communications",
    // opportunity1: ,
    // opportunity2: ,
    // risk1: ,
    // risk2: ,
    // snowflask: ,
  },
  {
    index: 2,
    id: "fsin",
    short_name: "F",
    name: "FlashIn, Inc.",
    overview:
      "FlashIn, Inc. (FSIN) is a fashion company based in France that designs and produces clothes, accessories, and sneakers. By 2072, FlashIn had started more than 1,000 retail stores worldwide. The company focuses on athletic apparel and streetwear, building a solid customer base among younger generations.",
    news_type: "6d3c59be-ec9e-442b-81c9-e4498ee670d2",
    industry: "Cons. Disc.",
    // opportunity1: ,
    // opportunity2: ,
    // risk1: ,
    // risk2: ,
    // snowflask: ,
  },
  {
    index: 3,
    id: "hhw",
    short_name: "W",
    name: "Hahawa & Co.",
    overview:
      "Hahawa & Co. (HHW) is an American chain of department stores founded in 1858 by Chinese immigrant Qing Hou. As of 2021, Hahawa was the largest U.S. department store company by retail sales with 608 physical department stores, including ten flagship stores, 178 magnet, 250 core, and 117 neighborhood stores.",
    news_type: "d7e6b3bd-d8a9-46ac-94f6-bb0f7ef94eee",
    industry: "Retail",
    // opportunity1: ,
    // opportunity2: ,
    // risk1: ,
    // risk2: ,
    // snowflask: ,
  },

  {
    index: 4,
    id: "jky",
    short_name: "J",
    name: "Jileky Investment, Inc.",
    overview:
      "Jileky Investment, Inc.(JKY) offers financial services among three major businesses: Corporate & Investment Bank, Commercial Banking, and Asset & Wealth Management. The company provides services to fulfill various client needs, including investment and lending products, deposit, cash management,…",
    news_type: "973458a0-eb3a-4e85-bd2a-f7513bf73bab",
    industry: "Financials",
    // opportunity1: ,
    // opportunity2: ,
    // risk1: ,
    // risk2: ,
    // snowflask: ,
  },
  {
    index: 5,
    id: "sgo",
    short_name: "S",
    name: "Surgo Corporation",
    overview:
      "Surgo (SGO) is a biomedical company that focuses on three segments: Medical devices, pharmaceuticals, and Consumer Health. It has established popularity through products in body lotion and facial cleansers. Recently, Surgo successfully invented AlphaTech, BetaTech, and other advanced surgical techs.",
    news_type: "5da3cc57-215d-413e-bae4-92d6b5d05e74",
    industry: "Healthcare",
    // opportunity1: ,
    // opportunity2: ,
    // risk1: ,
    // risk2: ,
    // snowflask: ,
  },
  {
    index: 5,
    id: "wrkn",
    short_name: "W",
    name: "Wakron, Inc.",
    overview:
      "Wakron, Inc. (WRKN) is a technology company headquartered in California, United States. The company develops products for people to connect and socialize with friends, families, and partners. Wakron’s main product WaKO, a decentralized platform for users to chat in text, video calls, and groups.",
    news_type: "d8488564-bc41-4874-a820-9ac245c07af1",
    industry: "I.T.",
    // opportunity1: ,
    // opportunity2: ,
    // risk1: ,
    // risk2: ,
    // snowflask: ,
  },
];

export default CompanyInfo;
