services:
  database:
    image: postgres
    ports:
      - "54321:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Xiaokeai0717
      POSTGRES_DB: aspect
  
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code