
version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Xiaokeai0717
      - POSTGRES_DB=aspect
    ports:
      - '10:10'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: aspect
    build: ./
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 10
      DB_USER: postgres
      DB_PASSWORD: Xiaokeai0717
      DB_NAME: aspect
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local