version: "2.1"

services:
  web:
    build: .
    ports:
      - 5000:5000

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: Xiaokeai0717
      POSTGRES_USER: postgres
    ports:
      - 5433:5432
    mem_limit: 128m

  postgres_admin:
    image: adminer
    container_name: postgres-admin
    ports:
      - 9095:8080
    mem_limit: 128m